version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///db.sqlite3

  db:
    image: "sqlite:latest"
    volumes:
      - ./data/db:/var/lib/sqlite
